INFO (event):
    id: 1956388900
    url: "https://api.github.com/repos/wrune/testturtl/pulls/7"
    node_id: "PR_kwDOMTBxRs50nCAk"
    html_url: "https://github.com/wrune/testturtl/pull/7"
    diff_url: "https://github.com/wrune/testturtl/pull/7.diff"
    patch_url: "https://github.com/wrune/testturtl/pull/7.patch"
    issue_url: "https://api.github.com/repos/wrune/testturtl/issues/7"
    number: 7
    state: "open"
    locked: false
    title: "edited this pr test.txt"
    user: {
      "login": "gagan-gaurav",
      "id": 51356017,
      "node_id": "MDQ6VXNlcjUxMzU2MDE3",
      "avatar_url": "https://avatars.githubusercontent.com/u/51356017?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gagan-gaurav",
      "html_url": "https://github.com/gagan-gaurav",
      "followers_url": "https://api.github.com/users/gagan-gaurav/followers",
      "following_url": "https://api.github.com/users/gagan-gaurav/following{/other_user}",
      "gists_url": "https://api.github.com/users/gagan-gaurav/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gagan-gaurav/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gagan-gaurav/subscriptions",
      "organizations_url": "https://api.github.com/users/gagan-gaurav/orgs",
      "repos_url": "https://api.github.com/users/gagan-gaurav/repos",
      "events_url": "https://api.github.com/users/gagan-gaurav/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gagan-gaurav/received_events",
      "type": "User",
      "site_admin": false
    }
    body: null
    created_at: "2024-07-07T10:23:03Z"
    updated_at: "2024-07-07T11:25:05Z"
    closed_at: null
    merged_at: null
    merge_commit_sha: "1d93c932e551f3087ad2caef2701aaacc945630b"
    assignee: null
    assignees: []
    requested_reviewers: []
    requested_teams: []
    labels: []
    milestone: null
    draft: false
    commits_url: "https://api.github.com/repos/wrune/testturtl/pulls/7/commits"
    review_comments_url: "https://api.github.com/repos/wrune/testturtl/pulls/7/comments"
    review_comment_url: "https://api.github.com/repos/wrune/testturtl/pulls/comments{/number}"
    comments_url: "https://api.github.com/repos/wrune/testturtl/issues/7/comments"
    statuses_url: "https://api.github.com/repos/wrune/testturtl/statuses/1ab5c19a24c4ee569641148c04ccf60f5b3c27fe"
    head: {
      "label": "wrune:test",
      "ref": "test",
      "sha": "1ab5c19a24c4ee569641148c04ccf60f5b3c27fe",
      "user": {
        "login": "wrune",
        "id": 146262631,
        "node_id": "O_kgDOCLfKZw",
        "avatar_url": "https://avatars.githubusercontent.com/u/146262631?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/wrune",
        "html_url": "https://github.com/wrune",
        "followers_url": "https://api.github.com/users/wrune/followers",
        "following_url": "https://api.github.com/users/wrune/following{/other_user}",
        "gists_url": "https://api.github.com/users/wrune/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/wrune/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wrune/subscriptions",
        "organizations_url": "https://api.github.com/users/wrune/orgs",
        "repos_url": "https://api.github.com/users/wrune/repos",
        "events_url": "https://api.github.com/users/wrune/events{/privacy}",
        "received_events_url": "https://api.github.com/users/wrune/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 825258310,
        "node_id": "R_kgDOMTBxRg",
        "name": "testturtl",
        "full_name": "wrune/testturtl",
        "private": true,
        "owner": {
          "login": "wrune",
          "id": 146262631,
          "node_id": "O_kgDOCLfKZw",
          "avatar_url": "https://avatars.githubusercontent.com/u/146262631?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/wrune",
          "html_url": "https://github.com/wrune",
          "followers_url": "https://api.github.com/users/wrune/followers",
          "following_url": "https://api.github.com/users/wrune/following{/other_user}",
          "gists_url": "https://api.github.com/users/wrune/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/wrune/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/wrune/subscriptions",
          "organizations_url": "https://api.github.com/users/wrune/orgs",
          "repos_url": "https://api.github.com/users/wrune/repos",
          "events_url": "https://api.github.com/users/wrune/events{/privacy}",
          "received_events_url": "https://api.github.com/users/wrune/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/wrune/testturtl",
        "description": "sole purpose of this repo is to create events for the reviewturtl",
        "fork": false,
        "url": "https://api.github.com/repos/wrune/testturtl",
        "forks_url": "https://api.github.com/repos/wrune/testturtl/forks",
        "keys_url": "https://api.github.com/repos/wrune/testturtl/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/wrune/testturtl/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/wrune/testturtl/teams",
        "hooks_url": "https://api.github.com/repos/wrune/testturtl/hooks",
        "issue_events_url": "https://api.github.com/repos/wrune/testturtl/issues/events{/number}",
        "events_url": "https://api.github.com/repos/wrune/testturtl/events",
        "assignees_url": "https://api.github.com/repos/wrune/testturtl/assignees{/user}",
        "branches_url": "https://api.github.com/repos/wrune/testturtl/branches{/branch}",
        "tags_url": "https://api.github.com/repos/wrune/testturtl/tags",
        "blobs_url": "https://api.github.com/repos/wrune/testturtl/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/wrune/testturtl/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/wrune/testturtl/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/wrune/testturtl/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/wrune/testturtl/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/wrune/testturtl/languages",
        "stargazers_url": "https://api.github.com/repos/wrune/testturtl/stargazers",
        "contributors_url": "https://api.github.com/repos/wrune/testturtl/contributors",
        "subscribers_url": "https://api.github.com/repos/wrune/testturtl/subscribers",
        "subscription_url": "https://api.github.com/repos/wrune/testturtl/subscription",
        "commits_url": "https://api.github.com/repos/wrune/testturtl/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/wrune/testturtl/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/wrune/testturtl/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/wrune/testturtl/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/wrune/testturtl/contents/{+path}",
        "compare_url": "https://api.github.com/repos/wrune/testturtl/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/wrune/testturtl/merges",
        "archive_url": "https://api.github.com/repos/wrune/testturtl/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/wrune/testturtl/downloads",
        "issues_url": "https://api.github.com/repos/wrune/testturtl/issues{/number}",
        "pulls_url": "https://api.github.com/repos/wrune/testturtl/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/wrune/testturtl/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/wrune/testturtl/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/wrune/testturtl/labels{/name}",
        "releases_url": "https://api.github.com/repos/wrune/testturtl/releases{/id}",
        "deployments_url": "https://api.github.com/repos/wrune/testturtl/deployments",
        "created_at": "2024-07-07T09:21:43Z",
        "updated_at": "2024-07-07T10:21:02Z",
        "pushed_at": "2024-07-07T11:18:15Z",
        "git_url": "git://github.com/wrune/testturtl.git",
        "ssh_url": "git@github.com:wrune/testturtl.git",
        "clone_url": "https://github.com/wrune/testturtl.git",
        "svn_url": "https://github.com/wrune/testturtl",
        "homepage": null,
        "size": 6,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 6,
        "license": null,
        "allow_forking": false,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "private",
        "forks": 0,
        "open_issues": 6,
        "watchers": 0,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    }
    base: {
      "label": "wrune:main",
      "ref": "main",
      "sha": "e7b44bb537d394f2e20efdd7975256bbe07abbf6",
      "user": {
        "login": "wrune",
        "id": 146262631,
        "node_id": "O_kgDOCLfKZw",
        "avatar_url": "https://avatars.githubusercontent.com/u/146262631?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/wrune",
        "html_url": "https://github.com/wrune",
        "followers_url": "https://api.github.com/users/wrune/followers",
        "following_url": "https://api.github.com/users/wrune/following{/other_user}",
        "gists_url": "https://api.github.com/users/wrune/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/wrune/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wrune/subscriptions",
        "organizations_url": "https://api.github.com/users/wrune/orgs",
        "repos_url": "https://api.github.com/users/wrune/repos",
        "events_url": "https://api.github.com/users/wrune/events{/privacy}",
        "received_events_url": "https://api.github.com/users/wrune/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 825258310,
        "node_id": "R_kgDOMTBxRg",
        "name": "testturtl",
        "full_name": "wrune/testturtl",
        "private": true,
        "owner": {
          "login": "wrune",
          "id": 146262631,
          "node_id": "O_kgDOCLfKZw",
          "avatar_url": "https://avatars.githubusercontent.com/u/146262631?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/wrune",
          "html_url": "https://github.com/wrune",
          "followers_url": "https://api.github.com/users/wrune/followers",
          "following_url": "https://api.github.com/users/wrune/following{/other_user}",
          "gists_url": "https://api.github.com/users/wrune/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/wrune/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/wrune/subscriptions",
          "organizations_url": "https://api.github.com/users/wrune/orgs",
          "repos_url": "https://api.github.com/users/wrune/repos",
          "events_url": "https://api.github.com/users/wrune/events{/privacy}",
          "received_events_url": "https://api.github.com/users/wrune/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/wrune/testturtl",
        "description": "sole purpose of this repo is to create events for the reviewturtl",
        "fork": false,
        "url": "https://api.github.com/repos/wrune/testturtl",
        "forks_url": "https://api.github.com/repos/wrune/testturtl/forks",
        "keys_url": "https://api.github.com/repos/wrune/testturtl/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/wrune/testturtl/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/wrune/testturtl/teams",
        "hooks_url": "https://api.github.com/repos/wrune/testturtl/hooks",
        "issue_events_url": "https://api.github.com/repos/wrune/testturtl/issues/events{/number}",
        "events_url": "https://api.github.com/repos/wrune/testturtl/events",
        "assignees_url": "https://api.github.com/repos/wrune/testturtl/assignees{/user}",
        "branches_url": "https://api.github.com/repos/wrune/testturtl/branches{/branch}",
        "tags_url": "https://api.github.com/repos/wrune/testturtl/tags",
        "blobs_url": "https://api.github.com/repos/wrune/testturtl/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/wrune/testturtl/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/wrune/testturtl/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/wrune/testturtl/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/wrune/testturtl/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/wrune/testturtl/languages",
        "stargazers_url": "https://api.github.com/repos/wrune/testturtl/stargazers",
        "contributors_url": "https://api.github.com/repos/wrune/testturtl/contributors",
        "subscribers_url": "https://api.github.com/repos/wrune/testturtl/subscribers",
        "subscription_url": "https://api.github.com/repos/wrune/testturtl/subscription",
        "commits_url": "https://api.github.com/repos/wrune/testturtl/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/wrune/testturtl/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/wrune/testturtl/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/wrune/testturtl/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/wrune/testturtl/contents/{+path}",
        "compare_url": "https://api.github.com/repos/wrune/testturtl/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/wrune/testturtl/merges",
        "archive_url": "https://api.github.com/repos/wrune/testturtl/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/wrune/testturtl/downloads",
        "issues_url": "https://api.github.com/repos/wrune/testturtl/issues{/number}",
        "pulls_url": "https://api.github.com/repos/wrune/testturtl/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/wrune/testturtl/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/wrune/testturtl/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/wrune/testturtl/labels{/name}",
        "releases_url": "https://api.github.com/repos/wrune/testturtl/releases{/id}",
        "deployments_url": "https://api.github.com/repos/wrune/testturtl/deployments",
        "created_at": "2024-07-07T09:21:43Z",
        "updated_at": "2024-07-07T10:21:02Z",
        "pushed_at": "2024-07-07T11:18:15Z",
        "git_url": "git://github.com/wrune/testturtl.git",
        "ssh_url": "git@github.com:wrune/testturtl.git",
        "clone_url": "https://github.com/wrune/testturtl.git",
        "svn_url": "https://github.com/wrune/testturtl",
        "homepage": null,
        "size": 6,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 6,
        "license": null,
        "allow_forking": false,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "private",
        "forks": 0,
        "open_issues": 6,
        "watchers": 0,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    }
    _links: {
      "self": {
        "href": "https://api.github.com/repos/wrune/testturtl/pulls/7"
      },
      "html": {
        "href": "https://github.com/wrune/testturtl/pull/7"
      },
      "issue": {
        "href": "https://api.github.com/repos/wrune/testturtl/issues/7"
      },
      "comments": {
        "href": "https://api.github.com/repos/wrune/testturtl/issues/7/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/wrune/testturtl/pulls/7/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/wrune/testturtl/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/wrune/testturtl/pulls/7/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/wrune/testturtl/statuses/1ab5c19a24c4ee569641148c04ccf60f5b3c27fe"
      }
    }
    author_association: "CONTRIBUTOR"
    auto_merge: null
    active_lock_reason: null
    merged: false
    mergeable: true
    rebaseable: true
    mergeable_state: "clean"
    merged_by: null
    comments: 10
    review_comments: 0
    maintainer_can_modify: false
    commits: 4
    additions: 8
    deletions: 0
    changed_files: 1